Handle all game events
kuredoro/snake_p2p pull request #14
Opened 2021-12-15 13:09 UTC by alphy1

Fixes #6

2021-12-15 15:33 UTC, kuredoro commented on engine/console/game.go
> +			}
A switch would look much cleaner. Additionally, you can just mutate the field in place, like
```
switch dir {
case core.Up:
    game.snakes[id].head.Y--
}
```

2021-12-15 15:33 UTC, kuredoro commented on engine/console/game.go
> +			for i := len(game.snakes[id].body) - 1; i > 0; i -= 1 {
`i--` instead of `i -= 1` would read much better.

2021-12-15 15:33 UTC, kuredoro commented on engine/console/game.go
> +		game.food[len(game.food) - 1] = core.Coord{X: 0, Y: 0}
You can omit initializing X, Y fields, because they will be zero-initialized by default: `core.Coord{}`.

2021-12-15 21:10 UTC, kuredoro commented on cmd/snakep2p/main.go
> +	startPlayerPos[3] = core.Coord{X: 10, Y: 6}
Please, use map literals to initialize variables to improve readability.
```
foo := map[int]int{
    42: 5,
    32: 1,
}
```

2021-12-15 21:10 UTC, kuredoro commented on cmd/snakep2p/main.go
>  	game.Ch <- core.Tick{}
This would be an impossible message sequence, since it follows a pattern:
```
PlayerStarts
Tick
PlayerMove
<some other events>
Tick
PlayerMove
<some other events>
Tick
PlayerMove
<some other events>
GameOver
```

Could you fix the order and check that the code still works?

2021-12-15 21:10 UTC, kuredoro commented on engine/console/game.go
> +		game.Food = game.Food[0:len(game.Food) - 1]
You can omit `0`...

2021-12-15 21:10 UTC, kuredoro commented on engine/console/game.go
> +		game.Food[len(game.Food) - 1] = core.Coord{}
Should not be needed... But it seems that game.Food should be a map too... You can delete elements from a map using `delete(game.Food, idx)`.

2021-12-15 21:10 UTC, kuredoro commented on engine/console/game.go
>  		s.Show()
Seems it doesn't draw anything properly at all, if I try to actually wait a second between each ticks... We should investigate in the next task...

2021-12-16 13:05 UTC, alphy1 commented on cmd/snakep2p/main.go
>  	game.Ch <- core.Tick{}
The problem is that game is over when 2 players are still alive, right?

2021-12-16 14:35 UTC, kuredoro commented on cmd/snakep2p/main.go
>  	game.Ch <- core.Tick{}
Not only.... I'm concerned that you have `Tick NewFood Tick`, instead of `Tick PlayerMove NewFood Tick` more...

2021-12-16 14:45 UTC, kuredoro commented on engine/console/game.go
> +	return game
Bad practice. Use struct literals to initialize structs:
```go
game := &Game{
    Ch: ch,
    Food: make(map[int]core.Coord),
    Snakes: make(map[int]*Snake),
    // ...
}
```

2021-12-16 14:45 UTC, kuredoro commented on engine/console/game.go
> +	Style tcell.Style  // snakep2p's style
Remove comments that duplicate what the name and the type say and make `alive` public, please.

2021-12-16 14:45 UTC, kuredoro commented on engine/console/game.go
> +	Snakes         map[int]*Snake   // snakes' state: alive snakes with ID, head and body coordinates
Better to rename to `AliveSnakes` and remove the comment.

2021-12-16 14:45 UTC, kuredoro commented on engine/console/game.go
> +	Over 	   	   bool				// whether game is over or not
The comments can be easily inferred from the variable's name and type. Consider removing them, please.

2021-12-16 14:45 UTC, kuredoro commented on engine/console/game.go
> +	Winner 		   int				// ID of the player who won the game
Better to rename to `WinnerID` and remove the comment.

2021-12-16 14:45 UTC, kuredoro commented on core/game_events.go
> +	ID int		// ID of snake
Better to rename to `SnakeID` and remove the comment.

2021-12-16 14:45 UTC, kuredoro commented on core/game_events.go
> +	ID int		// eaten food ID
Better to rename to `FoodID` and remove the comment (since one day, there also might be a `SnakeID`).

2021-12-16 14:45 UTC, kuredoro commented on core/game_events.go
>  }
These comments duplicate what the names and types of the variables say, consider removing them.

2021-12-16 17:38 UTC, kuredoro requested changes
Please, apply `gofmt -s -w .` in the repository root.

2021-12-16 17:38 UTC, kuredoro commented on engine/console/game.go
> +		WinnerID: -1}
Incorrect formatting, brace should be on a dedicated line.

2021-12-16 17:38 UTC, kuredoro commented on engine/console/game.go
> +	game := &Game {
Incorrect formatting, no space should be present before the brace.

2021-12-16 18:12 UTC, kuredoro approved these changes

2021-12-16 18:12 UTC, merged